producer:
  build: ./producer
  net: "nsolid"
  ports:
    - 3000:3000
  environment:
    - NODE_DEBUG=nsolid
    - NSOLID_APPNAME=producer
    - NSOLID_HUB=registry:4001
nginx:
  image: nginx
  volumes:
    - ./nginx/producer.conf:/etc/nginx/conf.d/producer.conf:ro
  net: "nsolid"
  ports:
    - 8080:8080
  links:
    - producer

#################################################
# Copy and Pasted from NodeSource Documentation #
#################################################
registry:
  image: nodesource/nsolid-registry
  container_name: registry
  net: "nsolid"
  ports:
    - 4001:4001
proxy:
  image: nodesource/nsolid-hub
  container_name: hub
  environment:
    - REGISTRY=registry:4001
    - NODE_DEBUG=nsolid
  net: "nsolid"
console:
  image: nodesource/nsolid-console
  container_name: console
  environment:
    - NODE_DEBUG=nsolid
  net: "nsolid"
  command: --hub hub:9000
  ports:
    - 3001:3000
